# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MartiPlacesApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MartiPlacesApp

	pod 'PromiseKit', "~> 6.8"
	pod 'Alamofire', '~> 5.2'
  	pod 'ObjectMapper', '~> 3.4'
	pod 'GoogleMaps', '~> 3.9.0'
	pod 'GooglePlaces'
	pod 'SnapKit', '~> 5.0.0'

  target 'MartiPlacesAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MartiPlacesAppUITests' do
    # Pods for testing
  end

end
